version: '3'

services:
  gf:
    container_name: gf
    build:
      context: gf
    networks:
      - txto_net
    volumes:
      - ../src/gf:/src/gf:rw

networks:
  txto_net:
    external: false
    name: txto_net
